### ISSUE TITLE
Import error for ipython 8.11.0

### ISSUE THREAD

**Issue by mukund109** [bragradon/ipython-copilot-completer#2]
<pre>File <font color="#859900">~/Documents/ipython-copilot-completer/copilot_completer/modes/key_binding.py:4</font>
<font color="#586E75"><b>      1</b></font> <font color="#008700"><b>from</b></font> <font color="#0000FF"><b>__future__</b></font> <font color="#008700"><b>import</b></font> annotations
<font color="#586E75"><b>      3</b></font> <font color="#008700"><b>from</b></font> <font color="#0000FF"><b>IPython</b></font> <font color="#008700"><b>import</b></font> get_ipython
<font color="#859900">----&gt; 4</font> <font color="#008700"><b>from</b></font> <font color="#0000FF"><b>IPython.terminal.shortcuts</b></font> <font color="#008700"><b>import</b></font> cursor_in_leading_ws
<font color="#586E75"><b>      5</b></font> <font color="#008700"><b>from</b></font> <font color="#0000FF"><b>prompt_toolkit.enums</b></font> <font color="#008700"><b>import</b></font> DEFAULT_BUFFER
<font color="#586E75"><b>      6</b></font> <font color="#008700"><b>from</b></font> <font color="#0000FF"><b>prompt_toolkit.filters</b></font> <font color="#008700"><b>import</b></font> (
<font color="#586E75"><b>      7</b></font>     HasFocus,
<font color="#586E75"><b>      8</b></font>     HasSelection,
<font color="#586E75"><b>      9</b></font>     emacs_insert_mode,
<font color="#586E75"><b>     10</b></font>     vi_insert_mode,
<font color="#586E75"><b>     11</b></font> )

<font color="#DC322F">ImportError</font>: cannot import name &apos;cursor_in_leading_ws&apos; from &apos;IPython.terminal.shortcuts&apos; (/home/mk/miniconda3/envs/py39/lib/python3.9/site-packages/IPython/terminal/shortcuts/__init__.py)
</pre>

**Comment by bragradon** [comment]
Thanks @mukund109 

I have updated the import and created a new wheel
